steps:
  - label: "run-loremipsum-sentence"
    key: "run_sentence" # Define a valid key for this step
    plugins:
      - docker#v3.8.0:
          image: "python:3.13"
    commands:
      - python -c "from loremipsum import sentence; print(sentence(max_char=20))" > result.txt
      - buildkite-agent annotate --style "info" --context "sentence" < result.txt

  - label: "run-loremipsum-paragraph"
    key: "run_paragraph" # Define a valid key for this step
    plugins:
      - docker#v3.8.0:
          image: "python:3.13"
    commands:
      - python -c "from loremipsum import paragraph; print(paragraph(max_char=100))" > paragraph.txt
      - buildkite-agent annotate --style "info" --context "paragraph" < paragraph.txt
    depends_on: "run_sentence" # Reference the key of the first step