steps:
  - label: ":speech_balloon: Generate sentence (max 20 chars)"
    key: sentence-step
    plugins:
      - docker#v5.10.0:
          image: python:3.13
          always-pull: true
    commands:
      - pip install py-lorem
      - python -c "from loremipsum import sentence; print(sentence(max_char=20))" > result.txt
    artifact_paths:
      - result.txt

  - label: ":memo: Annotate sentence"
    depends_on: sentence-step
    commands:
      - buildkite-agent artifact download result.txt .
      - buildkite-agent annotate --style 'info' --context 'sentence-output' "$(cat result.txt)"

  - label: ":page_facing_up: Generate paragraph (max 100 chars)"
    key: paragraph-step
    depends_on: sentence-step
    plugins:
      - docker#v5.10.0:
          image: python:3.13
          always-pull: true
    commands:
      - pip install py-lorem
      - python -c "from loremipsum import paragraph; print(paragraph(max_char=100))" > result.txt
    artifact_paths:
      - result.txt

  - label: ":memo: Annotate paragraph"
    depends_on: paragraph-step
    commands:
      - buildkite-agent artifact download result.txt .
      - buildkite-agent annotate --style 'info' --context 'paragraph-output' "$(cat result.txt)"
